"""Self-hosted fonts: trim Archivo to the axes the design uses, copy Atkinson,
and write src/styles/fonts.css.

The design only uses Archivo at weight 700-800 and width 62-90%, so the
variable font is cut to those ranges (90 KB -> 24 KB core + 17 KB accents). Re-run after
upgrading the @fontsource packages:

    python3 scripts/subset-fonts.py
"""
import io
import shutil
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

# Same unicode ranges as @fontsource, so latin-ext only downloads when a page needs it.
RANGES = {
    "latin": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "latin-ext": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
}
# Archivo's latin file is split again: "core" (plain letters, digits, common punctuation)
# is all most headings need and is the one preloaded (24 KB); "latin" holds the
# accented letters and only downloads on pages that use them. Ranges must not overlap.
ARCHIVO = {
    "core": ("latin", "U+0000-007E,U+00A0,U+00B7,U+2013-2014,U+2019,U+201C-201D,U+2026,U+20AC"),
    "latin": ("latin", "U+00A1-00B6,U+00B8-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,"
              "U+2000-2012,U+2015-2018,U+201A-201B,U+201E-2025,U+2027-206F,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"),
    "latin-ext": ("latin-ext", RANGES["latin-ext"]),
}

def unicodes(rng):
    out = []
    for part in rng.replace("U+", "").split(","):
        a, _, b = part.partition("-")
        out.extend(range(int(a, 16), int(b or a, 16) + 1))
    return out

css = ["/* Generated by scripts/subset-fonts.py. Do not edit. */"]
for name, (source, rng) in ARCHIVO.items():
    font = TTFont(f"node_modules/@fontsource-variable/archivo/files/archivo-{source}-wdth-normal.woff2")
    font = instantiateVariableFont(font, {"wght": (700, 800), "wdth": (62, 90)})
    buf = io.BytesIO()
    font.save(buf)  # round-trip: the subsetter needs fully loaded variation tables
    buf.seek(0)
    font = TTFont(buf)
    opts = subset.Options()
    opts.layout_features = ["*"]
    opts.notdef_outline = True
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=unicodes(rng))
    sub.subset(font)
    font.flavor = "woff2"
    font.save(f"public/fonts/archivo-{name}.woff2")
    css.append(f"@font-face {{ font-family: 'Archivo'; font-style: normal; font-display: swap; font-weight: 700 800; font-stretch: 62% 90%; src: url(/fonts/archivo-{name}.woff2) format('woff2'); unicode-range: {rng}; }}")

for subset_name, rng in RANGES.items():
    for w in ("400", "700"):
        shutil.copy(f"node_modules/@fontsource/atkinson-hyperlegible-next/files/atkinson-hyperlegible-next-{subset_name}-{w}-normal.woff2", f"public/fonts/atkinson-{subset_name}-{w}.woff2")
        # optional: body text never re-wraps after first paint (no layout shift); cached from the second page on.
        css.append(f"@font-face {{ font-family: 'Atkinson Hyperlegible Next'; font-style: normal; font-display: optional; font-weight: {w}; src: url(/fonts/atkinson-{subset_name}-{w}.woff2) format('woff2'); unicode-range: {rng}; }}")
# Arial sized to Atkinson's metrics, so swapping in the web font doesn't move text
# (no layout shift). Values from Atkinson Hyperlegible Next 400 vs Arial: average
# glyph width 0.481 vs 0.492 em, typo ascender 984, descender -316, UPM 1000.
css.append("@font-face { font-family: 'Atkinson Fallback'; src: local('Arial'), local('Liberation Sans'), local('Helvetica'); size-adjust: 97.87%; ascent-override: 100.55%; descent-override: 32.29%; line-gap-override: 0%; }")
with open("src/styles/fonts.css", "w") as f:
    f.write("\n".join(css) + "\n")
print("public/fonts + src/styles/fonts.css written")
